project:
  type: website
  output-dir: docs

website:
  title: "Todd Nobles"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: cv.qmd
        text: "CV"
      - href: research.qmd
        text: "Research"
      - href: teaching.qmd
        text: "Teaching"
      - href: vizzes.qmd
        text: "Visualizations and Tools"

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    link-external-icon: true
    link-external-newwindow: true




