---
title: "Research"
---

### Peer Reviewed Publications

Li Verdugo, J., **Nobles, T**, Herting, J. R., Lee, J. J., & Takeuchi, D. T. (2025). Socioeconomic factors and mental health among young Asian adults in the United States. Ethnicity & Health, 1–21. <https://doi.org/10.1080/13557858.2025.2600274>

### Submitted

Auguste, D., Kim, P., **Nobles, T.** (2026) Mirage of Success: Precarious Entrepreneurship, Long-term Unemployment, and Income Generation Challenges

### Working Papers

Increasingly Radical: Examining Predictors of Support for Reactionary Right-Wing Candidates for the United States House of Representatives

Enemy Aliens: German Interment during the First World War (with Peter Catron and Kate Stovel)

The Earnings Premium Puzzle of Entrepreneurial Experience: Who Benefits (with Daniel Auguste)

### Other Publications

Smither, C., **Nobles, T.**, Parsons, K., Mason, J. & Peek, A. Improving Measures of Student Progression: Lessons for Postsecondary Competency-Based Education Practitioners and Institutional Research Professionals. [Available here](https://www.air.org/sites/default/files/Improving-Measures-of-Student-ProgressionL-Lessons-for-Postsecondary-CBE-Practitioners-2019.pdf)
