---
title: "Teaching"
---

### Instructor

- SOC/CSSS/STAT 221: Statistical Concepts and Methods for the Social Sciences - Planned Summer 2026. [Syllabus](syllabi/SOC221_SUM26_Syllabus.pdf)

- SOC 300: Foundations of Social Inquiry - Summer 2025. [Syllabus](syllabi/SOC300_SUM25_Syllabus_20250703.pdf)

- Math Camp Summer 2025 and planned Summer 2026. [Syllabus](syllabi/Math Camp Syllabus Update 2026.pdf)

### Teaching Assistant

- SOC 506: Methodology: Quantitative Techniques in Sociology (*Graduate Course*) - Spring 2024

- SOC 505: Applied Social Statistics (*Graduate Course*) - Winter 2024 & Winter 2025

- SOC 504: Introduction to Applied Social Statistics (*Graduate Course*) - Autumn 2023 & Autumn 2024

- SOC 301: Labor Market Inequality (*Undergraduate Course*) - Spring 2023

- SOC 292: Who Gets Ahead? Public Schooling in America (*Undergraduate Course*) - Winter 2023

- SOC 225: Data and Society (*Undergraduate Course*) - Autumn 2022

### Tutoring

One of my most rewarding teaching experiences has been the opportunity to serve as a tutor for the first-year cohorts of Social Work and Social Welfare PhD students at the University of Washington through their year long introductory statistics course sequence from 2023-2026.
